[build-system]
requires = [
    'setuptools',
    'cython',
    'wheel'
]
build-backend = "setuptools.build_meta"

[tool.cibuildwheel]
skip = "pp*"

[tool.cibuildwheel.macos.environment]
MACOSX_DEPLOYMENT_TARGET = "10.9"  # required for full C++11 support
